// This dictionary is used for name creation purposes. It stores syllables and special names. When a dices is thrown, it will determine which syllable add to the current name.
export const nameSyllables = {
  "syllables": [
    "ma",
    "ne",
    "on",
    "ar",
    "ys",
    "ter",
    "io",
    "pa",
    "mi",
    "ga",
    "ni",
    "to",
    "re",
    "go",
    "zu",
    "de",
    "ci",
    "co",
    "ri",
    "si",
    "pi",
    "o",
    "ri",
    "te",
    "lu",
    "tri",
    "cu",
    "ra",
    "ge",
    "na",
    "za",
    "ze",
    "no",
    "ve",
    "ce",
    "que",
    "ta",
    "la",
    "bi",
    "an",
    "lo",
    "as",
    "tro",
    "cos",
    "mo",
    "lu",
    "na",
    "stel",
    "ga",
    "lax",
    "no",
    "va",
    "ce",
    "lest",
    "spec",
    "tro",
    "ori",
    "on",
    "aqua",
    "sol",
    "e",
    "clip",
    "se",
    "qua",
    "sar",
    "cos",
    "mic",
    "ze",
    "phyr",
    "ne",
    "ser",
    "a",
    "phin",
    "he",
    "lio",
    "lium",
    "lios",
    "ter",
    "lu",
    "min",
    "os",
    "ity",
    "vor",
    "tex",
    "as",
    "tral",
    "po",
    "la",
    "ris",
    "ne",
    "bu",
    "la",
    "ra",
    "diant",
    "zo",
    "diac",
    "ther",
    "au",
    "ro",
    "ra",
    "cyg",
    "nus",
    "so",
    "la",
    "ris",
    "ve",
    "ga",
    "lyr",
    "phan",
    "tom",
    "ly",
    "sy",
    "si",
    "ra",
    "ecli",
    "tic",
    "um",
    "bra",
    "te",
    "rra",
    "ae",
    "ro",
    "pyra",
    "cyron",
    "li",
    "thic",
    "qua",
    "xi",
    "on",
    "zo",
    "lo",
    "gy",
    "pha",
    "se",
    "bio",
    "tro",
    "pi",
    "co",
    "ni",
    "co",
    "ni",
    "thi",
    "te",
    "les",
    "ca",
    "le",
    "ther",
    "al",
    "no",
    "ve",
    "ry",
    "du",
    "al",
    "sta",
    "tic"
  ],
  "specials": [
    "XG-",
    "MTD-",
    "VOR-",
    "LUM-",
    "COS-",
    "AST-",
    "PLAS-",
    "SYN-",
    "ZEN-",
    "PYR-",
    "NEX-",
    "HYD-",
    "QUA-",
    "SOL-",
    "VER-",
    "TRI-",
    "PLUTO-",
    "GAL-",
    "SYR-",
    "ORI-",
    "CELE-",
    "VENT-",
    "XEN-",
    "CRYS-",
    "EXO-",
    "ASTRO-",
    "META-",
    "NEB-",
    "TECH-",
    "QUAD-",
    "UNI-",
    "SPECTR-",
    "OMNI-",
    "RADI-",
    "ULTRA-",
    "NANO-",
    "MAGN-",
    "QUANT-",
    "CIRCUIT-",
    "GEO-",
    "MEGA-",
    "HYPER-",
    "PROTO-",
    "ANTI-",
    "MAGNA-",
    "SONI-",
    "LITH-",
    "SYMI-",
    "PHOENIX-",
    "CRYPTO-",
    "ECHO-",
    "CRYPT-",
    "SYMI-",
    "CYBR-",
    "SUN-",
    "VENTI-",
    "ALTI-",
    "ASTRA-",
    "THERMO-",
    "CAPT-",
    "VOY-",
    "FLUX-",
    "FISS-",
    "MYSTI-",
    "VIR-",
    "ALPHA-",
    "TELE-",
    "ECHO-",
    "SONO-",
    "HELIO-",
    "NEO-",
    "GIGA-",
    "TURBO-",
    "INFINI-",
    "QUASAR-",
    "SOLAR-",
    "DECA-",
    "DYNAMO-",
    "LUX-",
    "NEURO-",
    "TESSER-"
  ]
}

// This is the list of possible biomes on the planets.
export const planetBiomes = ['Crystal Desert', 'Floating forest', 'Fog Ocean', 'Tomb',
'Gaia', 'Subterranean cities', 'Metallic Meadows',
'Crystal canyons', 'Magnetic skies', 'Luminous ice forest',
'Mirage desert', 'Floating meadows', 'Nebula Jungle',
'Volcanic Plateau', 'Coral Reefs of the Abyss',
'Aurora Plains', 'Electric Stormscape', 'Bioluminescent Caves',
'Silicon Dunes', 'Ancient Ruin Fields', 'Quicksilver Marsh',
'Gravity-defying Mountains', 'Toxic Haze Swamps',
'Ephemeral Blossom Valley', 'Obsidian Wasteland',
'Spectrum Rainforest', 'Time-Warp Tundra', 'Harmonic Meadows',
'Celestial Archipelago', 'Quantum Crystal Ridge',
'Inferno Craterlands', 'Galactic Garden']

// This is the list of possible biomes on the moons.
export const moonBiomes = ['Crater Highlands', 'Icy Regolith Plains', 'Lunar Caves', 
'Ethereal Ice Ridges', 'Dust Storm Basins', 'Polar Frostlands',
'Regolith Dunes', 'Cosmic Tundra', 'Abyssal Craters', 
'Galactic Plateaus', 'Lunar Lava Fields', 'Shadowed Valleys', 
'Chilled Impact Basins', 'Stellar Rugged Peaks', 
'Void Oasis', 'Frosty Tectonic Rifts', 'Lunar Mesas', 
'Gravity-defying Cliffs', 'Astral Ridge Network']

// List of probabilities for max number of moons for a planet. As the number grows, the possibilities get lower.
export const moonProbs = [0.25, 0.25, 0.2, 0.15, 0.07, 0.05, 0.02, 0.01]

// Same list but for planet probabilities.
export const planetProbs = [0.01, 0.085, 0.085, 0.088, 0.18, 0.199, 0.2, 0.07, 0.07, 0.065, 0.06, 0.05, 0.05, 0.04]

// This one is for the star probabilities, but instead of determine the max number in the system, it refers to the star type (Black hole, Yellow dwarf, etc)
export const starProbs = [0.043, 0.05, 0.074, 0.06, 0.277, 0.3, 0.2445, 0.05333, 0.05117]


